config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  get '/static_pages/privacy_policy', to: 'static_pages#privacy_policy'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, only: %i[new create index destroy]
  resources :investments, only: %i[new create show index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :stock, presence: true
  validates :bonds, presence: true
  validates :pachinko, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :investments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :show]
  def new
    @investment = Investment.new
  end

  def create
    if !Investment.find_by(user_id: current_user.id, month: 12)
    @investment = Investment.new(investment_params)
    @investment.user_id = current_user.id
    if @investment.stock.present? && @investment.bonds.present? && @investment.pachinko.present?
      @investment.saving = 100000000 - @investment.stock - @investment.bonds - @investment.pachinko
      @investment.total = @investment.stock + @investment.bonds + @investment.pachinko + @investment.saving
      @investment.month = 0
      if @investment.saving >= 0 && @investment.save
        1.upto(12) do |num|
          @investment = @investment.dup
          @investment.stock = @investment.stock * rand(4..23) /11.to_f
          @investment.bonds = @investment.bonds * rand(8..17) /11.to_f
          @investment.pachinko = @investment.pachinko * rand(1..11) /10.to_f
          @investment.total = @investment.stock + @investment.bonds + @investment.pachinko + @investment.saving
          @investment.month = num
          @investment.save
        end
        #binding.irb
        redirect_to @investment
      else
        flash.now[:danger] = '投資することが出来ませんでした'
        #binding.irb
        render :new
      end
    else
      flash.now[:danger] = '入力してください'
      render :new
    end
    else
      flash.now[:danger] = '既に相談しています'
      render :new
    end
  end

  def show
    @result = Investment.find_by(user_id: current_user.id, month: 12)
    @investments = Investment.where(user_id: current_user.id).includes(:user).order(month: :asc)
  end

  def index
    @investments = Investment.where(month: 12).order(total: :desc).limit(10)
  end

  private

  def investment_params
    params.require(:investment).permit(:stock, :bonds, :pachinko)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in user
      redirect_to user
    else
      render root_path
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to new_investment_path
    else
      flash.now[:danger] = '名前が未入力です'
      render :new
    end
  end

  def index
    @investments = Investment.where(month: 12).paginate(page: params[:page], per_page: 20).order(created_at: :desc)
  end

  def destroy
    @user = User.find_by(id: session[:user_id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
    #binding.irb
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
      #binding.irb
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

    # beforeアクション

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      flash[:danger] = "名前を入力してください"
      redirect_to root_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/investments/index.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-12">
      <h1>
        <span>成金</span>
        <span class="font_red">らんきんぐ</span>
      </h1>
      <div>
        <%= link_to '戻る', root_path %>
      </div>

      <div class="users">
        <% if @investments.present? %>
          <% @investments.each.with_index(1) do |investment, i| %>
            <li>
              <%= image_tag 'moguro.png',width: '100px', height: '120px', class: "image_list" %>
              <%= "#{i}位：「#{investment.user.name}」" %>
              <% if investment.total > 300000000 %>
                <span class="font_green"><%= "　→　億万長者！" %></span>
              <% else %>
                <span class="font_red"><%= "　→　破産" %></span>
              <% end %>
              <br><br>
              <% if investment.total > 300000000 %>
              <span><%= "最終：" %></span>
              <span class="font_green"><%= "#{investment.total.to_j}円"%></span><br><%= "（債権: #{investment.bonds.to_j}円、株式: #{investment.stock.to_j}円、"%><br class="visible-xs-block"><%= "パチンコ: #{investment.pachinko.to_j}円、貯金: #{investment.saving.to_j}円）" %>
              <% else %>
              <span><%= "最終：" %></span>
              <span class="font_red"><%= "#{investment.total.to_j}円"%></span><br><%= "（債権: #{investment.bonds.to_j}円、株式: #{investment.stock.to_j}円、"%><br class="visible-xs-block"><%= "パチンコ: #{investment.pachinko.to_j}円、貯金: #{investment.saving.to_j}円）" %>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <p><%= 'まだ誰も相談していません' %></p>
        <% end %>
      </div>

    </div>
  </div>
  <div>
    <%= link_to '戻る', root_path %>
  </div>
</div>

app/views/investments/new.html.erb
<%= render 'shared/flash_message' %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>
        <span class="font_red">
          笑ゥ
        </span>
        <br class="visible-xs-block"><span>
          ぎんこうまん とは
        </span>
      </h1>
      <div class="balloon3">
        <p>喪黒金造は、<br><%= "貧困に悩む#{current_user.name}に、" %><br class="visible-xs-block"><span class="font_red">1億円</span>を貸してくれました。<br>
            ただし1年後には、<span class="font_red">3億円</span>で<br class="visible-xs-block">返さなくてはいけません。<br>投資でお金を増やしましょう。<br><br>もし返せなかったら。。。
        </p>
      </div>
      <%= form_with model: @investment, local: true do |f| %>
          <div class="form-group">
            <span class="font_green"><%= f.label :①債権（低リスク＆低リターン） %></span>
            <br><%= f.select :bonds, [["投資しない", "0"],["1,000万円", "10000000"], ["2,000万円", "20000000"], ["3,000万円", "30000000"], ["4,000万円", "40000000"], ["5,000万円", "50000000"], ["6,000万円", "60000000"], ["7,000万円", "70000000"], ["8,000万円", "80000000"], ["9,000万円", "90000000"], ["1億円", "100000000"]], class: 'form-control' %>
          </div>
          <div class="form-group">
            <span class="font_yellow"><%= f.label :②株式（高リスク＆高リターン）  %></span>
            <br><%= f.select :stock, [["投資しない", "0"],["1,000万円", "10000000"], ["2,000万円", "20000000"], ["3,000万円", "30000000"], ["4,000万円", "40000000"], ["5,000万円", "50000000"], ["6,000万円", "60000000"], ["7,000万円", "70000000"], ["8,000万円", "80000000"], ["9,000万円", "90000000"], ["1億円", "100000000"]], class: 'form-control' %>
          </div>
          <div class="form-group">
            <span class="font_red"><%= f.label :③パチンコ（高リスク＆低リターン）  %></span>
            <br><%= f.select :pachinko, [["投資しない", "0"],["1,000万円", "10000000"], ["2,000万円", "20000000"], ["3,000万円", "30000000"], ["4,000万円", "40000000"], ["5,000万円", "50000000"], ["6,000万円", "60000000"], ["7,000万円", "70000000"], ["8,000万円", "80000000"], ["9,000万円", "90000000"], ["1億円", "100000000"]], class: 'form-control' %>
          <br><br>※残額は④貯金（無リスク＆無リターン）<br class="visible-xs-block">になります。<br><br>
          <div class="actions">
            <%= f.submit '投資する', class: 'btn btn-default btn-lg' %>
          </div>
      <% end %>
      <div class='text-center'>
        <%= link_to '相談をやめる', user_path(current_user), method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/investments/show.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-12">
      <h1>
        <span>1年後、、、</span>
        <br class="visible-xs-block">
        <% if @result.total > 300000000 %>
        <span class="font_green"><%= "#{@result.total.to_j}円" %></span>
        <% else %>
        <span class="font_red"><%= "#{@result.total.to_j}円" %></span>
        <% end %>
      </h1>
      <h1 class="font_red">
        <% if @result.total > 300000000 %>
          <%= image_tag 'moguro.png',width: '300px', height: '350px', class: "image_list" %>
          <br><span class="font_green"><%= "#{current_user.name}は"%></span><span class="font_green"><br class="visible-xs-block">無事借金を返済できました！</span>
        <% else %>
          <%= image_tag 'moguro.png',width: '300px', height: '350px', class: "image_list" %>
          <br><span><%= "#{current_user.name}は"%></span><span><br class="visible-xs-block">破産しました</span>
        <% end %>
      </h1>
      <div>
        <% if @result.total > 300000000 %>
          <%= link_to 'Twitterに投稿する', url = "https://twitter.com/intent/tweet?text=1億円が1年後...#{@result.total.to_j}円！%0A「#{current_user.name}」は借金返して億万長者！もう闇金なんて怖くない！%0Ahttps://cryptic-retreat-09777.herokuapp.com/%0A%23笑ゥぎんこうまん", class: 'btn btn-default btn-lg' %>
          <br><br><%= link_to '戻る', logout_path, method: :delete %>
        <% else %>
          <%= link_to 'Twitterで救いを求める', url = "https://twitter.com/intent/tweet?text=1億円が1年後...#{@result.total.to_j}円！%0A「#{current_user.name}」は借金を返せず破産しました。誰か助けて下さい！%0Ahttps://cryptic-retreat-09777.herokuapp.com/%0A%23笑ゥぎんこうまん", class: 'btn btn-default btn-lg' %>
          <br><br><%= link_to '戻る', logout_path, method: :delete %>
        <% end %>
      </div>
      <%= line_chart Investment.where(user_id: current_user.id).pluck(:month, :total), curve: false, discrete: true, colors: ["#fff", "#fff"] %>

      <div class="users">
        <% if @investments.present? %>
          <% @investments.each do |investment| %>
            <li>
              <% if investment.total > 300000000 %>
                <%= "#{investment.month}ヶ月目" %>
                <span class="font_green"><%= "#{investment.total.to_j}円"%></span><br><%= "（債権: #{investment.bonds.to_j}円、株式: #{investment.stock.to_j}円、"%><br class="visible-xs-block"><%= "パチンコ: #{investment.pachinko.to_j}円、貯金: #{investment.saving.to_j}円）" %>
              <% else %>
                <%= "#{investment.month}ヶ月目" %>
                <span class="font_red"><%= "#{investment.total.to_j}円"%></span><br><%= "（債権: #{investment.bonds.to_j}円、株式: #{investment.stock.to_j}円、"%><br class="visible-xs-block"><%= "パチンコ: #{investment.pachinko.to_j}円、貯金: #{investment.saving.to_j}円）" %>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <p><%= '投資結果がありません' %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <%= link_to '戻る', logout_path, method: :delete %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <%= link_to 'プライバシーポリシー', static_pages_privacy_policy_path %>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="twitter:card" content="summary_large_image" /> <!--①-->
    <meta name="twitter:site" content="@mfy7qGso9YNuGfK" /> <!--②-->
    <meta property="og:url" content="https://cryptic-retreat-09777.herokuapp.com/" /> <!--③-->
    <meta property="og:title" content="笑ゥぎんこうまん" /> <!--④-->
    <meta property="og:description" content="お金を増やして、借金を返済しよう" /> <!--⑤-->
    <meta property="og:image" content="<%= asset_url('moguro.png') %>" /> <!--⑥-->
    <!--フォントの読み込み-->
    <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-JYBXP4RPZL"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-JYBXP4RPZL');
    </script>
  </head>
    <title>LaughingMillionaire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/8.7.1/firebase-app.js"></script>

  <!-- TODO: Add SDKs for Firebase products that you want to use
      https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="https://www.gstatic.com/firebasejs/8.7.1/firebase-analytics.js"></script>

  <script>
    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    var firebaseConfig = {
      apiKey: "AIzaSyDc6Mff9UsYQRqfmh6XN93eBN21KBm_3zY",
      authDomain: "sample-dd7e7.firebaseapp.com",
      projectId: "sample-dd7e7",
      storageBucket: "sample-dd7e7.appspot.com",
      messagingSenderId: "900802970765",
      appId: "1:900802970765:web:0d24e0f63bfe77b8e34ec4",
      measurementId: "G-K4NBHDLCTM"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages_html.erb
 <% if object.errors.any? %>
   <div id="error_messages" class="alert alert-danger">
     <ul class="mb-0">
       <% object.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/static_pages/privacy_policy.html.erb
<div class="container">
    <h2>
プライバシーポリシー
    </h2>
    <div>
      <p>当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を使用しています。</p>
      <p>このGoogleアナリティクスはデータの収集のためにCookieを使用しています。このデータは匿名で収集されており、個人を特定するものではありません。 この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブラウザの設定をご確認ください。</p>
      <p>この規約に関しての詳細は<a href="https://marketingplatform.google.com/about/analytics/terms/jp/">Googleアナリティクスサービス利用規約</a>のページや<a href="https://policies.google.com/technologies/ads?hl=ja">Googleポリシーと規約</a>ページをご覧ください。</p>
    </div>
    <br><%= image_tag 'moguro.png',width: '300px', height: '350px' %>
    <br><br><div class='text-center'>
      <%= link_to '戻る', root_path %>
    </div>
  </div>

app/views/static_pages/top.html.erb
<html>
  <head>
    <!--フォントの読み込み-->
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
  </head>
  <body>
  <div class="container">
    <h1>
      <span class="font_red">
        笑ゥ
      </span>
      <br class="visible-xs-block"><span>
        ぶぁんかぁ
      </span>
    </h1>
    <div class="balloon2">
      <p>私の名は喪黒<span class="font_yellow">金</span>造、人呼んで<br class="visible-xs-block">「笑ゥぶぁんかぁ」。<br>私の取り扱う品物は<span class="font_red">富</span>、<br class="visible-xs-block"><span class="font_red">人間の夢</span>でございます。<br class="visible-xs-block">ホーホッホッ…<br><br>
      <p>この世は老いも若きも男も女も、<br class="visible-xs-block">貧乏人ばかり、<br>そんな皆さんの<span class="font_red">”財布”</span>をお埋め致します。<br><br><br class="visible-xs-block">さて、今日のお客様は…</p>
    </div>
    <br><%= image_tag 'moguro.png',width: '25%', height: '25%' %>
    <br><%= link_to "相談する", new_user_path, class: 'btn btn-default btn-lg' %>
    <div class='text-center'>
      <%= link_to '他人の人生を見てみる', users_path %>
    </div>
  </div>
  </body>
</html>

app/views/users/index.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-12">
      <h1>
        <span>みんなの</span>
        <span class="font_red">成れ果て</span>
      </h1>
      <div>
        <%= link_to '戻る', root_path %>
      </div>

      <%= will_paginate @investments, previous_label: '&lt 前へ', next_label: '次へ &gt' %>

      <div class="users">
        <% if @investments.present? %>
          <% @investments.each do |investment| %>
            <li>
              <%= image_tag 'moguro.png',width: '100px', height: '120px', class: "image_list" %>
              <%= "・#{investment.user.name}" %>
              <% if investment.total > 300000000 %>
                <span class="font_green"><%= "　→　億万長者！" %></span>
              <% else %>
                <span class="font_red"><%= "　→　破産" %></span>
              <% end %>
              <br><br>
              <% if investment.total > 300000000 %>
              <span><%= "最終：" %></span>
              <span class="font_green"><%= "#{investment.total.to_j}円"%></span><br><%= "（債権: #{investment.bonds.to_j}円、株式: #{investment.stock.to_j}円、"%><br class="visible-xs-block"><%= "パチンコ: #{investment.pachinko.to_j}円、貯金: #{investment.saving.to_j}円）" %>
              <% else %>
              <span><%= "最終：" %></span>
              <span class="font_red"><%= "#{investment.total.to_j}円"%></span><br><%= "（債権: #{investment.bonds.to_j}円、株式: #{investment.stock.to_j}円、"%><br class="visible-xs-block"><%= "パチンコ: #{investment.pachinko.to_j}円、貯金: #{investment.saving.to_j}円）" %>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <p><%= 'まだ誰も相談していません' %></p>
        <% end %>
      </div>

      <%= will_paginate @investments, previous_label: '&lt 前へ', next_label: '次へ &gt' %>

    </div>
  </div>
  <div>
    <%= link_to '戻る', root_path %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'shared/flash_message' %>

<html>
  <head>
    <!--フォントの読み込み-->
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
  </head>
  <body>
  <div class="container">
    <h1>
      <span class="font_red">
        笑ゥ
      </span>
      <br class="visible-xs-block"><span>
        ぎんこうまん
      </span>
    </h1>
    <div class="balloon2">
      <p>私の名は喪黒<span class="font_yellow">金</span>造（もぐろ かねぞう）、<br class="visible-xs-block">人呼んで「笑ゥぎんこうまん」。<br>私の取り扱う品物は<span class="font_red">富</span>、<br class="visible-xs-block"><span class="font_red">人間の欲</span>でございます。<br class="visible-xs-block">ホーホッホッ…<br><br>
      <p>この世は老いも若きも男も女も、<br class="visible-xs-block">貧乏人ばかり、<br>そんな皆さんの<span class="font_red">”財布”</span>をお埋め致します。<br><br><br class="visible-xs-block">さて、今日のお客様は…</p>
    </div>
    <br><%= image_tag 'moguro.png',width: '300px', height: '350px' %>
    <br><br><%= form_with model: @user, local: true do |f| %>
      <div class="form-group">
        <%= f.label :お名前 %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit '相談する', class: 'btn btn-default btn-lg' %>
      </div>
    <% end %>

    <div class='text-center'>
      <%= link_to '他人の人生を見てみる', users_path %>
      <br><%= link_to '成金らんきんぐ', investments_path %>
    </div>
  </div>
  </body>
</html>